[pytest]
markers =
    api: API tests
    ui: UI tests
    smoke: critical tests
    negative: negative test cases
    integration: API + UI combined tests
addopts = -v --html=report.html --self-contained-html