name: Run Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Install Playwright
        run: |
          pip install playwright
          playwright install
      
      - name: Run Smoke tests
        run: PYTHONPATH=. pytest -m smoke -v

      - name: Run API tests
        run: PYTHONPATH=. pytest -m api -v
      
      - name: Run UI tests
        run: PYTHONPATH=. pytest -m ui -v
        env:
          HEADLESS: "true"
          SLOW_MO: "0"